import os
from modules import cmd_args
parser = cmd_args.parser
cmd_opts = parser.parse_args()

fast_models = {
    '3D Animation Diffusion v1.safetensors':'https://huggingface.co/romisyed/sdnew/resolve/main/3D%20Animation%20Diffusion%20v1.safetensors',
    'A-Zovya Photoreal v2.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/A-Zovya%20Photoreal%20v2.safetensors',
    'AbsoluteReality v1.6.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/AbsoluteReality%20v1.6.safetensors',
    'AbyssOrangeMix3.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/AbyssOrangeMix3.safetensors',
    'AnyHentai v2.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/AnyHentai%20v2.safetensors',
    'AnyLoRA.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/AnyLoRA.safetensors',
    'Anything v5.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/Anything%20v5.safetensors',
    'Beautiful Realistic Asians v6.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/Beautiful%20Realistic%20Asians%20v6.safetensors',
    'CetusMix Whalefall 2.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/CetusMix%20Whalefall%202.safetensors',
    'Cheese Daddy Landscapes Mix v4.1.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/Cheese%20Daddy%20Landscapes%20Mix%20v4.1.safetensors',
    'ChikMix v3.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/Cheese%20Daddy%20Landscapes%20Mix%20v4.1.safetensors',
    'ChilloutMix.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/ChilloutMix.safetensors',
    'Clarity 2.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/Clarity%202.safetensors',
    'Colorful v3.1.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/Colorful%20v3.1.safetensors',
    'Counterfeit v3.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/Counterfeit%20v3.safetensors',
    'CyberRealistic v3.2.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/CyberRealistic%20v3.2.safetensors',
    'Dark Sushi Mix.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/Dark%20Sushi%20Mix.safetensors',
    'Deliberate v2.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/Deliberate%20v2.safetensors',
    'DreamFul v3.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/DreamFul%20v3.safetensors',
    'Dreamlike Photoreal 2.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/Dreamlike%20Photoreal%202.safetensors',
    'DreamShaper 8.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/DreamShaper%208.safetensors',
    'Edge Of Realism v2.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/Edge%20Of%20Realism%20v2.safetensors',
    'Epic Diffusion v1.1.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/Epic%20Diffusion%20v1.1.safetensors',
    'epiCRealism v4.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/epiCRealism%20v4.safetensors',
    'Experience 8.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/Experience%208.safetensors',
    'GhostMix v2.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/GhostMix%20v2.safetensors',
    'HappyDiffusionFX.safetensors' : 'https://huggingface.co/romisyed/sd/resolve/main/HappyDiffusionFX.safetensors',
    'HARDblend.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/HARDblend.safetensors',
    'Hassaku v1.3.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/Hassaku%20v1.3.safetensors',
    'Henmix Real v4.safetensors':'https://huggingface.co/romisyed/sdnew/resolve/main/Henmix%20Real%20v4.safetensors',
    'ICBINP v8.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/ICBINP%20v8.safetensors',
    'Juggernaut Aftermath.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/Juggernaut%20Aftermath.safetensors',
    'Level4 v5.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/Level4%20v5.safetensors',
    'Liberty.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/Liberty.safetensors',
    'Life Like Diffusion v2.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/Life%20Like%20Diffusion%20v2.safetensors',
    'LOFI v3.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/LOFI%20v3.safetensors',
    'majicMIX realistic v2.5.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/majicMIX%20realistic%20v2.5.safetensors',
    'MeinaMix v11.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/MeinaMix%20v11.safetensors',
    'NeverEnding Dream v1.22.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/NeverEnding%20Dream%20v1.22.safetensors',
    'OnlyRealistic v30.safetensors':'https://huggingface.co/romisyed/sdnew/resolve/main/OnlyRealistic%20v30.safetensors',
    'Perfect World v5.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/Perfect%20World%20v5.safetensors',
    'Photon v1.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/Photon%20v1.safetensors',
    'Protogen x3.4.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/Protogen%20x3.4.safetensors',
    'RealCartoon3D v5.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/RealCartoon3D%20v5.safetensors',
    'Realisian v5.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/Realisian%20v5.safetensors',
    'Realistic Vision v5.1.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/Realistic%20Vision%20v5.1.safetensors',
    'ReV Animated v1.2.2.safetensors': 'https://huggingface.co/romisyed/sdnew/resolve/main/ReV%20Animated%20v1.2.2.safetensors',
    'RealCartoon3D v6.safetensors':'https://huggingface.co/romisyed/sdnew/resolve/main/RealCartoon3D%20v6.safetensors',
    'Reliberate v1.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/Reliberate%20v1.safetensors',
    'RPG v5.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/RPG%20v5.safetensors',
    'Stable Diffusion v1.5.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/Stable%20Diffusion%20v1.5.safetensors',
    'Stable Diffusion v2.1.safetensors': 'https://huggingface.co/romisyed/sdnew/resolve/main/Stable%20Diffusion%20v2.1.safetensors',
    'SunshineMix＆SunlightMix.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/SunshineMix%EF%BC%86SunlightMix.safetensors',
    'UniverseStable v5.safetensors': 'https://huggingface.co/romisyed/sdnew/resolve/main/UniverseStable%20v5.safetensors',
    'XXMix 9realistic v4.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/XXMix%209realistic%20v4.safetensors',

}

other_models = {
    '3D Animation Diffusion v1.safetensors': 'https://huggingface.co/romisyed/sdnew/resolve/main/3D%20Animation%20Diffusion%20v1.safetensors',
    'A-Zovya Photoreal v2.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/A-Zovya%20Photoreal%20v2.safetensors',
    'AbsoluteReality v1.6.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/AbsoluteReality%20v1.6.safetensors',
    'AbyssOrangeMix3.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/AbyssOrangeMix3.safetensors',
    'AnyHentai v2.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/AnyHentai%20v2.safetensors',
    'AnyLoRA.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/AnyLoRA.safetensors',
    'Anything v5.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/Anything%20v5.safetensors',
    'Beautiful Realistic Asians v6.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/Beautiful%20Realistic%20Asians%20v6.safetensors',
    'CetusMix Whalefall 2.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/CetusMix%20Whalefall%202.safetensors',
    'Cheese Daddy Landscapes Mix v4.1.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/Cheese%20Daddy%20Landscapes%20Mix%20v4.1.safetensors',
    'ChikMix v3.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/Cheese%20Daddy%20Landscapes%20Mix%20v4.1.safetensors',
    'ChilloutMix.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/ChilloutMix.safetensors',
    'Clarity 2.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/Clarity%202.safetensors',
    'Colorful v3.1.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/Colorful%20v3.1.safetensors',
    'Counterfeit v3.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/Counterfeit%20v3.safetensors',
    'CyberRealistic v3.2.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/CyberRealistic%20v3.2.safetensors',
    'Dark Sushi Mix.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/Dark%20Sushi%20Mix.safetensors',
    'Deliberate v2.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/Deliberate%20v2.safetensors',
    'DreamFul v3.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/DreamFul%20v3.safetensors',
    'Dreamlike Photoreal 2.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/Dreamlike%20Photoreal%202.safetensors',
    'DreamShaper 8.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/DreamShaper%208.safetensors',
    'Edge Of Realism v2.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/Edge%20Of%20Realism%20v2.safetensors',
    'Epic Diffusion v1.1.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/Epic%20Diffusion%20v1.1.safetensors',
    'epiCRealism v4.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/epiCRealism%20v4.safetensors',
    'Experience 8.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/Experience%208.safetensors',
    'GhostMix v2.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/GhostMix%20v2.safetensors',
    'HappyDiffusionFX.safetensors' : 'https://huggingface.co/romisyed/sd/resolve/main/HappyDiffusionFX.safetensors',
    'HARDblend.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/HARDblend.safetensors',
    'Hassaku v1.3.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/Hassaku%20v1.3.safetensors',
    'Henmix Real v4.safetensors': 'https://huggingface.co/romisyed/sdnew/resolve/main/Henmix%20Real%20v4.safetensors',
    'ICBINP v8.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/ICBINP%20v8.safetensors',
    'Juggernaut Aftermath.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/Juggernaut%20Aftermath.safetensors',
    'Level4 v5.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/Level4%20v5.safetensors',
    'Liberty.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/Liberty.safetensors',
    'Life Like Diffusion v2.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/Life%20Like%20Diffusion%20v2.safetensors',
    'LOFI v3.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/LOFI%20v3.safetensors',
    'majicMIX realistic v2.5.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/majicMIX%20realistic%20v2.5.safetensors',
    'MeinaMix v11.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/MeinaMix%20v11.safetensors',
    'NeverEnding Dream v1.22.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/NeverEnding%20Dream%20v1.22.safetensors',
    'OnlyRealistic v30.safetensors': 'https://huggingface.co/romisyed/sdnew/resolve/main/OnlyRealistic%20v30.safetensors',
    'Perfect World v5.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/Perfect%20World%20v5.safetensors',
    'Photon v1.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/Photon%20v1.safetensors',
    'Protogen x3.4.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/Protogen%20x3.4.safetensors',
    'RealCartoon3D v5.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/RealCartoon3D%20v5.safetensors',
    'Realisian v5.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/Realisian%20v5.safetensors',
    'Realistic Vision v5.1.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/Realistic%20Vision%20v5.1.safetensors',
    'ReV Animated v1.2.2.safetensors':'https://huggingface.co/romisyed/sdnew/resolve/main/ReV%20Animated%20v1.2.2.safetensors',
    'RealCartoon3D v6.safetensors': 'https://huggingface.co/romisyed/sdnew/resolve/main/RealCartoon3D%20v6.safetensors',
    'Reliberate v1.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/Reliberate%20v1.safetensors',
    'RPG v5.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/RPG%20v5.safetensors',
    'Stable Diffusion v1.5.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/Stable%20Diffusion%20v1.5.safetensors',
    'Stable Diffusion v2.1.safetensors':'https://huggingface.co/romisyed/sdnew/resolve/main/Stable%20Diffusion%20v2.1.safetensors',
    'Stable Diffusion XL v1.safetensors': 'https://huggingface.co/romisyed/sdnew/resolve/main/Stable%20Diffusion%20XL%20v1.safetensors',
    'SunshineMix＆SunlightMix.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/SunshineMix%EF%BC%86SunlightMix.safetensors',
    'UniverseStable v5.safetensors':'https://huggingface.co/romisyed/sdnew/resolve/main/UniverseStable%20v5.safetensors',
    'XXMix 9realistic v4.safetensors': 'https://huggingface.co/romisyed/sd/resolve/main/XXMix%209realistic%20v4.safetensors',

}

_provided_checkpoints = fast_models if cmd_opts.exclude else other_models
